server:
  context-path: /practice
  port: 8090
  session:
    timeout: 18000
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false
    username: root
    password: MyNewPass
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: update
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  data.jpa.repositories.enabled: true